name: draft-workflow
on:
    push:
        branches:
            - workflow
jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: '14'
            - uses: actions/cache@v2
              id: node-deps-cache
              with:
                path: |
                    ~/.npm
                    *
                key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            - if: steps.node-deps-cache.outputs.cache-hit != 'true'
              run: npm ci
            - if: steps.node-deps-cache.outputs.cache-hit != 'true'
              run: npm install netlify-cli -g
    build:
        needs: setup
        runs-on: ubuntu-latest
        steps:
            - uses: actions/cache@v2
              with:
                path: |
                    ~/.npm
                    *
                key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            - run: npm run build
    test:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/cache@v2
              with:
                path: |
                    ~/.npm
                    *
                key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            - run: npm run test